### ISSUE TITLE
执行提示”TypeError: Cannot read property 'bizCode' of undefined“，哪里不对了？

### ISSUE THREAD

**Issue by gnowmil** [curtinlv/JD-Script#55]
每次执行都出错，是哪里配置不正确吗？用的青龙2.8，其他都正常的。
日志如下：
❗️东东超市兑换奖品, 错误!
TypeError: Cannot read property 'bizCode' of undefined
    at /ql/scripts/shufflewzc_faker2_jd_blueCoin.js:372:27
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/shufflewzc_faker2_jd_blueCoin.js:491:4869)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by curtinlv** [comment]
你好，我的是python版本。
